### PR TITLE
Added Support for Spawn-Protection Instead of Spawn-Radius, and Adventure default Gamemode

### PR DESCRIPTION
**Pull request by Lunaphied**
I don't quite know how to add an adventure button in the players screen. As this control panel is still regularly maintained, I expect that these will be useful.

### CODE REVIEW

**Comment by Antariano** [comment]
I'll do the players page :P But I'm not sure about your third commit, why are you changing that to dev builds?
The craftbukkit chooser page displays the latest rb on top and then a  table of dev builds already.

**Comment by Lunaphied** [comment]
It didn't for me, also I made the changes based on the current code, I
don't know more than basic php, what in all is needed? I want to fix
the avatar for the players page but couldn't figure out where that
code was.

**Comment by Antariano** [comment]
If the avatars don't display that might be because your php_gd2 extension is not loaded. 
Does your server page look like this? http://puu.sh/1wmFN

**Comment by Lunaphied** [comment]
umm i think so... I use my dev commit changes.

**Comment by Lunaphied** [comment]
Whats the status as this?

**Comment by Antariano** [comment]
@modwizcode Could you split those commits into different PRs?

**Comment by Lunaphied** [comment]
Yes I will work on that.

**Pull request closed without merging**
